# failure-threshold: info
format: tty
label-schema:
  org.opencontainers.image.url: url
  org.opencontainers.image.source: url
  org.opencontainers.image.vendor: text
  org.opencontainers.image.title: text
  org.opencontainers.image.description: text
  org.opencontainers.image.documentation: url
  org.opencontainers.image.authors: text
  org.opencontainers.image.licenses: spdx
  org.opencontainers.image.base.name: text
trustedRegistries:
  - docker.io
